import '../models/admin_stats.dart';
import '../models/booking.dart';
import '../models/message.dart';
import '../models/project.dart';
import '../models/skill_listing.dart';

class DemoData {
  static final List<SkillListing> skillListings = [
    const SkillListing(
      id: 101,
      userId: 2,
      title: 'Laravel Live Q&A',
      description: 'Quick guidance for building REST APIs with Laravel.',
      durationMinutes: 60,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Ariana Patel',
      userUsername: 'ariana_dev',
    ),
    const SkillListing(
      id: 102,
      userId: 3,
      title: 'API Design Best Practices',
      description: 'Create clean endpoints, authentication, and API versioning.',
      durationMinutes: 30,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Marcus Lee',
      userUsername: 'marcus_api',
    ),
    const SkillListing(
      id: 103,
      userId: 4,
      title: 'Database Migrations & Eloquent',
      description: 'Build scalable models and migrations for Laravel apps.',
      durationMinutes: 60,
      expertiseLevel: 'beginner',
      isActive: true,
      userName: 'Nina Brooks',
      userUsername: 'ninab',
    ),
    const SkillListing(
      id: 104,
      userId: 5,
      title: 'Authentication with Sanctum',
      description: 'Secure your API with token-based login and logout flows.',
      durationMinutes: 120,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Julian Park',
      userUsername: 'julian_auth',
    ),
    const SkillListing(
      id: 105,
      userId: 6,
      title: 'Flutter & Laravel Integration',
      description: 'Connect a Flutter mobile app to a Laravel REST API backend.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Lina Ortiz',
      userUsername: 'lina_mobile',
    ),
    const SkillListing(
      id: 106,
      userId: 7,
      title: 'Eloquent Relationships',
      description: 'Model one-to-many and many-to-many relationships in Laravel.',
      durationMinutes: 30,
      expertiseLevel: 'beginner',
      isActive: true,
      userName: 'Carlos Reed',
      userUsername: 'carl_dev',
    ),
    const SkillListing(
      id: 107,
      userId: 8,
      title: 'API Validation & Error Handling',
      description: 'Build robust validation rules and user-friendly API errors.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Tara Singh',
      userUsername: 'tara_api',
    ),
    const SkillListing(
      id: 108,
      userId: 9,
      title: 'TDD for Laravel APIs',
      description: 'Write backend tests for endpoints, requests, and authentication.',
      durationMinutes: 120,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Ethan Ward',
      userUsername: 'ethan_test',
    ),
    const SkillListing(
      id: 109,
      userId: 10,
      title: 'SEO-ready project structure',
      description: 'Design backend APIs with clean route and controller organization.',
      durationMinutes: 30,
      expertiseLevel: 'beginner',
      isActive: true,
      userName: 'Maya Flynn',
      userUsername: 'maya_dev',
    ),
    const SkillListing(
      id: 110,
      userId: 11,
      title: 'Laravel notifications & mail',
      description: 'Send alerts and confirmation emails from your REST API.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Oliver Grant',
      userUsername: 'oliver_notify',
    ),
    const SkillListing(
      id: 111,
      userId: 12,
      title: 'Debugging Laravel APIs',
      description: 'Use logging and exception handling to diagnose backend issues.',
      durationMinutes: 45,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Sofia Chen',
      userUsername: 'sofia_debug',
    ),
    const SkillListing(
      id: 112,
      userId: 13,
      title: 'Pivot tables & many-to-many',
      description: 'Manage advanced database relationships with Laravel Eloquent.',
      durationMinutes: 60,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Noah Kim',
      userUsername: 'noah_sync',
    ),
    const SkillListing(
      id: 113,
      userId: 14,
      title: 'GraphQL APIs with Laravel',
      description: 'Build modern GraphQL endpoints for frontend apps.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Priya Singh',
      userUsername: 'priya_graphql',
    ),
    const SkillListing(
      id: 114,
      userId: 15,
      title: 'Unit Testing Controllers',
      description: 'Write tests for Laravel controllers and request validation.',
      durationMinutes: 45,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Samuel Diaz',
      userUsername: 'sam_test',
    ),
    const SkillListing(
      id: 115,
      userId: 16,
      title: 'REST API Authentication',
      description: 'Implement secure login and token refresh flows.',
      durationMinutes: 90,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Mina Park',
      userUsername: 'mina_auth',
    ),
    const SkillListing(
      id: 116,
      userId: 17,
      title: 'Server-side Caching',
      description: 'Use caching to improve API performance and reduce load.',
      durationMinutes: 30,
      expertiseLevel: 'beginner',
      isActive: true,
      userName: 'Jared Cole',
      userUsername: 'jared_cache',
    ),
    const SkillListing(
      id: 117,
      userId: 18,
      title: 'Laravel Events & Listeners',
      description: 'Create event-driven flows for notifications and analytics.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Anna Lee',
      userUsername: 'anna_events',
    ),
    const SkillListing(
      id: 118,
      userId: 19,
      title: 'Payment Integration with Stripe',
      description: 'Connect Laravel apps to Stripe for secure payments.',
      durationMinutes: 120,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Kyle Brown',
      userUsername: 'kyle_pay',
    ),
    const SkillListing(
      id: 119,
      userId: 20,
      title: 'API Rate Limiting',
      description: 'Implement throttling controls for endpoint protection.',
      durationMinutes: 30,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Nora Feng',
      userUsername: 'nora_rate',
    ),
    const SkillListing(
      id: 120,
      userId: 21,
      title: 'Polymorphic Relationships',
      description: 'Model reusable relationships across different entities.',
      durationMinutes: 45,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Diego Rivera',
      userUsername: 'diego_poly',
    ),
    const SkillListing(
      id: 121,
      userId: 22,
      title: 'Localization & Multilingual Apps',
      description: 'Build multilingual user experiences in Laravel and Flutter.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Zara Khan',
      userUsername: 'zara_locale',
    ),
    const SkillListing(
      id: 122,
      userId: 23,
      title: 'Social Login Implementation',
      description: 'Add Google and Facebook login to your backend.',
      durationMinutes: 60,
      expertiseLevel: 'intermediate',
      isActive: true,
      userName: 'Leon Liu',
      userUsername: 'leon_social',
    ),
    const SkillListing(
      id: 123,
      userId: 24,
      title: 'Database Seeding Best Practices',
      description: 'Create seeders and factory data for development and testing.',
      durationMinutes: 30,
      expertiseLevel: 'beginner',
      isActive: true,
      userName: 'Mia Torres',
      userUsername: 'mia_seed',
    ),
    const SkillListing(
      id: 124,
      userId: 25,
      title: 'Secure API File Uploads',
      description: 'Handle file uploads safely with validation and storage.',
      durationMinutes: 90,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Owen Blake',
      userUsername: 'owen_upload',
    ),
    const SkillListing(
      id: 125,
      userId: 26,
      title: 'Laravel Notifications & Queues',
      description: 'Send queued emails and push updates reliably.',
      durationMinutes: 60,
      expertiseLevel: 'advanced',
      isActive: true,
      userName: 'Tina Vo',
      userUsername: 'tina_queue',
    ),
  ];

  static final List<Project> projects = [
    Project(
      id: 201,
      title: 'Community Events Booking API',
      description: 'Build a Laravel API for managing event registrations and schedules.',
      status: 'open',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
      skillsNeeded: ['API', 'Laravel', 'Testing'],
      rewardCredits: 18,
    ),
    Project(
      id: 202,
      title: 'Mobile App Backend for Skill Marketplace',
      description: 'Create endpoints to support a mobile skill marketplace with bookings.',
      status: 'in_progress',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      skillsNeeded: ['Laravel', 'REST', 'Database'],
      rewardCredits: 25,
    ),
    Project(
      id: 203,
      title: 'Mentorship Match Engine',
      description: 'Design a recommendation API for matching learners with mentors.',
      status: 'open',
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
      skillsNeeded: ['Machine Learning', 'Laravel', 'SQL'],
      rewardCredits: 20,
    ),
    Project(
      id: 204,
      title: 'Credit Wallet Reward System',
      description: 'Implement wallet earning, spending, and reward tracking.',
      status: 'completed',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 6)),
      skillsNeeded: ['Laravel', 'Payments', 'Notifications'],
      rewardCredits: 0,
    ),
    Project(
      id: 205,
      title: 'Portfolio Showcase Dashboard',
      description: 'Build a user dashboard for displaying completed projects and skills.',
      status: 'open',
      createdAt: DateTime.now().subtract(const Duration(hours: 20)),
      skillsNeeded: ['UI', 'Flutter', 'Backend'],
      rewardCredits: 15,
    ),
    Project(
      id: 206,
      title: 'User Reputation Calculator',
      description: 'Create logic to score reliability, community engagement, and learning progress.',
      status: 'in_progress',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
      skillsNeeded: ['Laravel', 'Analytics', 'Data'],
      rewardCredits: 22,
    ),
    Project(
      id: 207,
      title: 'Skill Search Algorithm',
      description: 'Improve search relevance for skills, topics, and teacher expertise.',
      status: 'open',
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
      skillsNeeded: ['Search', 'Laravel', 'UX'],
      rewardCredits: 14,
    ),
    Project(
      id: 208,
      title: 'Mentor Messaging System',
      description: 'Create a simple chat service to connect mentors and students.',
      status: 'completed',
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      skillsNeeded: ['Messaging', 'APIs', 'Notifications'],
      rewardCredits: 0,
    ),
  ];

  static final List<Message> messages = [
    Message(
      id: 301,
      senderId: 2,
      recipientId: 1,
      content: 'Hi! I am interested in your Laravel Q&A session this week.',
      createdAt: DateTime.now().subtract(const Duration(hours: 2, minutes: 10)),
      senderName: 'Ariana Patel',
      bookingId: 101,
    ),
    Message(
      id: 302,
      senderId: 3,
      recipientId: 1,
      content: 'Can we review the API validation errors together?',
      createdAt: DateTime.now().subtract(const Duration(hours: 4)),
      senderName: 'Marcus Lee',
    ),
    Message(
      id: 303,
      senderId: 4,
      recipientId: 1,
      content: 'Your recent project looks great — I have some feedback.',
      createdAt: DateTime.now().subtract(const Duration(hours: 7, minutes: 30)),
      senderName: 'Nina Brooks',
    ),
    Message(
      id: 304,
      senderId: 5,
      recipientId: 1,
      content: 'When is the next mentoring session scheduled?',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 1)),
      senderName: 'Julian Park',
      bookingId: 102,
    ),
    Message(
      id: 305,
      senderId: 6,
      recipientId: 1,
      content: 'I need help connecting Flutter to the backend.',
      createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 5)),
      senderName: 'Lina Ortiz',
    ),
  ];

  static final List<Booking> bookings = [
    Booking(
      id: 401,
      studentId: 1,
      teacherId: 2,
      skillListingId: 101,
      status: 'confirmed',
      durationMinutes: 60,
      scheduledAt: DateTime.now().add(const Duration(days: 1, hours: 2)),
      teacherName: 'Ariana Patel',
      skillTitle: 'Laravel Live Q&A',
      notes: 'Bring your API questions and schema diagrams.',
    ),
    Booking(
      id: 402,
      studentId: 1,
      teacherId: 3,
      skillListingId: 102,
      status: 'requested',
      durationMinutes: 30,
      scheduledAt: DateTime.now().add(const Duration(days: 2, hours: 1)),
      teacherName: 'Marcus Lee',
      skillTitle: 'API Design Best Practices',
    ),
    Booking(
      id: 403,
      studentId: 1,
      teacherId: 4,
      skillListingId: 103,
      status: 'completed',
      durationMinutes: 60,
      scheduledAt: DateTime.now().subtract(const Duration(days: 1, hours: 4)),
      teacherName: 'Nina Brooks',
      skillTitle: 'Database Migrations & Eloquent',
    ),
    Booking(
      id: 404,
      studentId: 1,
      teacherId: 5,
      skillListingId: 104,
      status: 'confirmed',
      durationMinutes: 120,
      scheduledAt: DateTime.now().add(const Duration(days: 3, hours: 4)),
      teacherName: 'Julian Park',
      skillTitle: 'Authentication with Sanctum',
    ),
    Booking(
      id: 405,
      studentId: 1,
      teacherId: 6,
      skillListingId: 105,
      status: 'requested',
      durationMinutes: 60,
      scheduledAt: DateTime.now().add(const Duration(days: 4)),
      teacherName: 'Lina Ortiz',
      skillTitle: 'Flutter & Laravel Integration',
    ),
    Booking(
      id: 406,
      studentId: 1,
      teacherId: 7,
      skillListingId: 106,
      status: 'confirmed',
      durationMinutes: 30,
      scheduledAt: DateTime.now().add(const Duration(hours: 20)),
      teacherName: 'Carlos Reed',
      skillTitle: 'Eloquent Relationships',
    ),
    Booking(
      id: 407,
      studentId: 1,
      teacherId: 8,
      skillListingId: 107,
      status: 'confirmed',
      durationMinutes: 60,
      scheduledAt: DateTime.now().add(const Duration(days: 1, hours: 8)),
      teacherName: 'Tara Singh',
      skillTitle: 'API Validation & Error Handling',
    ),
    Booking(
      id: 408,
      studentId: 1,
      teacherId: 9,
      skillListingId: 108,
      status: 'requested',
      durationMinutes: 120,
      scheduledAt: DateTime.now().add(const Duration(days: 5)),
      teacherName: 'Ethan Ward',
      skillTitle: 'TDD for Laravel APIs',
    ),
    Booking(
      id: 409,
      studentId: 1,
      teacherId: 10,
      skillListingId: 110,
      status: 'confirmed',
      durationMinutes: 60,
      scheduledAt: DateTime.now().add(const Duration(days: 2, hours: 3)),
      teacherName: 'Oliver Grant',
      skillTitle: 'Laravel notifications & mail',
    ),
    Booking(
      id: 410,
      studentId: 1,
      teacherId: 11,
      skillListingId: 111,
      status: 'confirmed',
      durationMinutes: 45,
      scheduledAt: DateTime.now().add(const Duration(days: 1, hours: 12)),
      teacherName: 'Sofia Chen',
      skillTitle: 'Debugging Laravel APIs',
    ),
    Booking(
      id: 411,
      studentId: 1,
      teacherId: 12,
      skillListingId: 112,
      status: 'requested',
      durationMinutes: 60,
      scheduledAt: DateTime.now().add(const Duration(days: 6)),
      teacherName: 'Noah Kim',
      skillTitle: 'Pivot tables & many-to-many',
    ),
  ];

  static const AdminStats adminStats = AdminStats(
    totalUsers: 1540,
    activeUsers: 482,
    sessionsCompleted: 890,
    creditsCirculated: 6700,
    popularSkills: [
      SkillStat(title: 'Laravel APIs', count: 245),
      SkillStat(title: 'Flutter Integration', count: 190),
      SkillStat(title: 'Eloquent Design', count: 140),
      SkillStat(title: 'Authentication', count: 100),
    ],
  );
}
